[build]
    command = npm run build
    base = /opt/build/VeggieYum/veggiemeal
    commandOrigin = ui
    environment = 
        - REACT_APP_API_KEY
    publish = /opt/build/VeggieYum/veggiemeal/public
    publishOrigin = ui

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200