[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
    redirectsOrigin = "config"

    [build]
        base = "/veggiemeal"
        command = "npm run build"
        commandOrigin = "ui"
        environment = "REACT_APP_API_KEY"
        publish = "/veggiemeal/build"
        publishOrigin = "ui"