[build]
    command = "npm run build"
    base = "/veggiemeal"
    commandOrigin = "ui"
    environment = "- REACT_APP_API_KEY"
    publish = "/veggiemeal/public"
    publishOrigin = "ui"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200